version: "3"
services:
    lighttpd:
        image: sebp/lighttpd
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - 8008:80
        volumes:
            - C:/mid_2:/var/www/localhost/htdocs
        tty: true